System.NullReferenceException: لم يتم تعيين مرجع كائن لمثيل كائن.
   عند Reflector.CodeModel.Assembly.TableReader.get_Item(Int32 tableType)
   عند Reflector.CodeModel.Assembly.Module.DecodeFieldPointerTable()
   عند Reflector.CodeModel.Assembly.Module.DecodeMetaData()
   عند Reflector.CodeModel.Assembly.Module.get_Types()
   عند Reflector.CodeModel.Assembly.Equality.ResolveTypeReference(ITypeReference typeReference, HashSet`1 alreadyChecked)
   عند Reflector.CodeModel.Assembly.TypeReference.Resolve(HashSet`1 alreadyChecked)
   عند Reflector.CodeModel.Assembly.Equality.ResolveTypeReference(ITypeReference typeReference, HashSet`1 alreadyChecked)
   عند Reflector.CodeModel.Assembly.TypeReference.Resolve(HashSet`1 alreadyChecked)
   عند Reflector.CodeModel.Assembly.CustomAttribute.GetUnderlyingFieldType(IType value)
   عند Reflector.CodeModel.Assembly.CustomAttribute.ReadValue(ByteArrayReader reader, IType type)
   عند Reflector.CodeModel.Assembly.CustomAttribute.get_Arguments()
   عند Reflector.Disassembler.Helper.IsTypeForward(ICustomAttribute customAttribute, ITypeReference& type)
   عند Reflector.CodeModel.Assembly.Assembly.AddCustomAttribute(ICustomAttribute customAttribute)
   عند Reflector.CodeModel.Assembly.Module.DecodeAssemblyCustomAttributes()
   عند Reflector.CodeModel.Assembly.Assembly.LoadAttributesIfNeeded()
   عند Reflector.CodeModel.Assembly.Assembly.get_TypeForwardedTo()
   عند Reflector.CodeModel.Assembly.Equality.ResolveTypeReference(ITypeReference typeReference, HashSet`1 alreadyChecked)
   عند Reflector.CodeModel.Assembly.TypeReference.Resolve(HashSet`1 alreadyChecked)
   عند Reflector.Disassembler.Optimizations.AssignStatementOptimizer.CanResolve(IType type)
   عند Reflector.Disassembler.Optimizations.AssignStatementOptimizer.CanResolve(IType type)
   عند Reflector.Disassembler.Optimizations.AssignStatementOptimizer.TransformExpression(IExpression expression, IType targetType)
   عند Reflector.Disassembler.Optimizations.AssignStatementOptimizer.TransformMethodReturnStatement(IMethodReturnStatement statement)
   عند Reflector.CodeModel.Visitor.Transformer.TransformStatement(IStatement value)
   عند Reflector.CodeModel.Visitor.Transformer.InsituTransformStatementCollection(IStatementCollection value)
   عند Reflector.CodeModel.Visitor.Transformer.TransformBlockStatement(IBlockStatement value)
   عند Reflector.CodeModel.Visitor.Transformer.TransformStatement(IStatement value)
   عند Reflector.CodeModel.Visitor.Transformer.TransformMethodDeclaration(IMethodDeclaration value)
   عند Reflector.Disassembler.Optimizations.ContextTransformer.TransformMethodDeclaration(IMethodDeclaration value)
   عند Reflector.Disassembler.Optimizations.AssignStatementOptimizer.TransformMethodDeclaration(IMethodDeclaration value)
   عند Reflector.Disassembler.Optimizer.Transform[T](IMethodDeclaration value, String typeName)
   عند Reflector.Disassembler.Optimizer.TransformMethodDeclaration(IMethodDeclaration value)
   عند Reflector.Disassembler.Disassembler.TransformMethodDeclaration(IMethodDeclaration value)
   عند Reflector.CodeModel.Visitor.Transformer.TransformMethodDeclarationCollection(IMethodDeclarationCollection methods)
   عند Reflector.Disassembler.Disassembler.TransformTypeDeclaration(ITypeDeclaration value)
   عند Reflector.Application.Translator.TranslateTypeDeclaration(ITypeDeclaration value, Boolean memberDeclarationList, Boolean methodDeclarationBody)
   عند Reflector.Application.FileDisassembler.WriteTypeDeclaration(ITypeDeclaration typeDeclaration, String sourceFile, ILanguageWriterConfiguration languageWriterConfiguration)
Namespace TaxGrad.My
End Namespace

