//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grad_Tax.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class States
    {
        public int ID_States { get; set; }
        public string States_Name { get; set; }
        public Nullable<int> id_User { get; set; }
    }
}
